### PR TITLE
put output txt files next to images

### PR DESCRIPTION
**Pull request by geoffpotter**
This change will save .txt files next to the images they're made for, instead of in the base output directory.   csv file is unaffected.

### CODE REVIEW

**Comment by Tps-F** [comment]
For my part, I do not believe that the text should be in the same directory as the images every time.

**Comment by geoffpotter** [comment]
I couldn't think of any workflows where you'd want them somewhere else, but I could add a checkbox that turns this functionality on and off if that would help.  I mainly need this for mass captioning a bunch of files in a directory structure, and dumping all the text files into the base directory isn't helpful, although I do want the csv file there for making regularization images.

**Comment by Tps-F** [comment]
Is it a hassle to set the output directory each time?

**Comment by geoffpotter** [comment]
Not for single directories, but I want to do all sub directories as well.  If the input folder has sub directories, it successfully grabs all those images and captions them, but it flattens the output directory structure amd puts all the text files in that directory.

I guess instead of a checkbox we could use the input dir and output directories being the same?  I guess if your output directory was different, you likely don't want this functionality.

**Comment by Tps-F** [comment]
@geoffpotter It is a bug. I'll fix it. Thanks!

**Pull request closed without merging**
